# Generated by Django 5.1.3 on 2025-01-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ing', models.ImageField(upload_to='image/')),
                ('courseName', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('full_price', models.IntegerField()),
                ('offer', models.CharField(max_length=25)),
            ],
        ),
    ]
