# Generated by Django 5.1.3 on 2025-01-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
