# Generated by Django 5.1.3 on 2025-01-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_cou_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
